name: external actions
on: push

jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout private actions repo
        uses: actions/checkout@v2
        with:
          repository: rushilshakya/actions
          path: actions/
          ref: dist
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: ./actions/hello
        name: action from external private repo
        id: runActionOutside
        with:
          who-to-greet: outside rushil
      - run: echo "${{ steps.runActionOutside.outputs.time }}"
