name: Expressions 1
on: push 

jobs:
  print_variables:
    runs-on: ubuntu-latest
    steps:
      - name: double curly
        run: |
          echo ${{ github.workflow }}
          echo "${{ github.workflow }}"
      - name: single curly
        run: |
          echo ${GITHUB_WORKFLOW}
          echo "${GITHUB_WORKFLOW}"
      - name: no curly
        run: |
          echo $GITHUB_WORKFLOW
          echo "$GITHUB_WORKFLOW"
