name: Expressions 2
on:
  workflow_run:
    workflows: ["Expressions 1"]
    types: [completed]

jobs:
  env_vars:
   runs-on: ubuntu-latest
  # if: ${{ github.event.workflow_run.conclusion == 'success' }}
   env: 
     GITHUB_CONTEXT: ${{ toJSON(github) }}
   steps:
     - uses: actions/checkout@v2
       with:
          ref: ${{ github.event.workflow_run.head_branch }}
     - name: run no curly
       run: echo $GITHUB_CONTEXT
     - name: run single curly
       run: echo ${GITHUB_CONTEXT}
     - name: run double cury
       run: echo ${GITHUB_CONTEXT}  