name: Expressions 2
on: push 

jobs:
  env_vars:
   runs-on: ubuntu-latest
   needs:
     - print_variables
   env: 
     GITHUB_CONTEXT: ${{ toJSON(github) }}
   steps:
     - name: run no curly
       run: echo $GITHUB_CONTEXT
     - name: run single curly
       run: echo ${GITHUB_CONTEXT}
     - name: run double cury
       run: echo ${GITHUB_CONTEXT}  