name: Expressions 2
on:
  workflow_run:
    workflows: ["Expressions 1"]
    branches: [Expressions]
    types: [completed]

jobs:
  env_vars:
   runs-on: ubuntu-latest
  # if: ${{ github.event.workflow_run.conclusion == 'success' }}
   env: 
     GITHUB_CONTEXT: ${{ toJSON(github) }}
   steps:
     - name: run no curly
       run: echo $GITHUB_CONTEXT
     - name: run single curly
       run: echo ${GITHUB_CONTEXT}
     - name: run double cury
       run: echo ${GITHUB_CONTEXT}  